(define (problem problema) (:domain agricultura)
(:objects
Pirey-C-48-50_1 Pirey-C-48-50_4 Ninguna_parcela - parcela

)

(:init
(=(costo)0)
(at 1 (periodo_del_plan))
(at 26 (not(periodo_del_plan)))
 (=(cantidad_ha_cultivo Papa)5)
(at 1 (not(temporada_papa)))
(at 2 (not(temporada_papa)))
(at 3 (not(temporada_papa)))
(at 4 (not(temporada_papa)))
(at 5 (not(temporada_papa)))
(at 6 (not(temporada_papa)))
(at 7 (not(temporada_papa)))
(at 8 (not(temporada_papa)))
(at 9 (not(temporada_papa)))
(at 10 (not(temporada_papa)))
(at 11 (temporada_papa))
(at 12 (temporada_papa))
(at 13 (not(temporada_papa)))
(at 14 (not(temporada_papa)))
(at 15 (not(temporada_papa)))
(at 16 (not(temporada_papa)))
(at 17 (not(temporada_papa)))
(at 18 (not(temporada_papa)))
(at 19 (not(temporada_papa)))
(at 20 (not(temporada_papa)))
(at 21 (not(temporada_papa)))
(at 22 (not(temporada_papa)))
(at 23 (temporada_papa))
(at 24 (temporada_papa))
(at 25 (not(temporada_papa)))
(at 26 (not(temporada_papa)))
(at 1 (parcela_libre Pirey-C-48-50_1))
(ultimo_cultivo Pirey-C-48-50_1 Ningun_cultivo)
(parcelas_vecinas Pirey-C-48-50_1 Ninguna_parcela)
(parcelas_vecinas Pirey-C-48-50_4 Ninguna_parcela)
(at 1 (parcela_libre Pirey-C-48-50_4))
(ultimo_cultivo Pirey-C-48-50_4 Ningun_cultivo)
(parcelas_vecinas Pirey-C-48-50_1 Ninguna_parcela)
(parcelas_vecinas Pirey-C-48-50_4 Ninguna_parcela)
(rotacion Papa Ningun_cultivo)
(rotacion Ningun_cultivo Papa )
(=(cantidad_ha_parcela Pirey-C-48-50_1)6.2536)
(=(coeficiente Pirey-C-48-50_1 Papa)0.75)
(=(cantidad_ha_parcela Pirey-C-48-50_4)6.2536)
(=(coeficiente Pirey-C-48-50_4 Papa)0.75)
)(:goal (and
(<=(cantidad_ha_cultivo Papa)0)
))
 (:metric minimize (costo))
)