(define (problem problema) (:domain agricultura)
(:objects
Albarran-3_3 Albarran-3_2 Albarran-2_1 Ninguna_parcela - parcela

)

(:init
(at 1 (periodo_del_plan))
(at 37 (not(periodo_del_plan)))
 (=(cantidad_ha_cultivo Papa)1)
(at 1 (not(temporada_papa)))
(at 2 (not(temporada_papa)))
(at 3 (not(temporada_papa)))
(at 4 (not(temporada_papa)))
(at 5 (not(temporada_papa)))
(at 6 (not(temporada_papa)))
(at 7 (not(temporada_papa)))
(at 8 (not(temporada_papa)))
(at 9 (not(temporada_papa)))
(at 10 (not(temporada_papa)))
(at 11 (temporada_papa))
(at 12 (temporada_papa))
(at 13 (not(temporada_papa)))
(at 14 (not(temporada_papa)))
(at 15 (not(temporada_papa)))
(at 16 (not(temporada_papa)))
(at 17 (not(temporada_papa)))
(at 18 (not(temporada_papa)))
(at 19 (not(temporada_papa)))
(at 20 (not(temporada_papa)))
(at 21 (not(temporada_papa)))
(at 22 (not(temporada_papa)))
(at 23 (temporada_papa))
(at 24 (temporada_papa))
(at 25 (not(temporada_papa)))
(at 26 (not(temporada_papa)))
(at 27 (not(temporada_papa)))
(at 28 (not(temporada_papa)))
(at 29 (not(temporada_papa)))
(at 30 (not(temporada_papa)))
(at 31 (not(temporada_papa)))
(at 32 (not(temporada_papa)))
(at 33 (not(temporada_papa)))
(at 34 (not(temporada_papa)))
(at 35 (temporada_papa))
(at 36 (temporada_papa))
(at 37 (not(temporada_papa)))
 (=(cantidad_ha_cultivo Tomate)1)
(at 1 (temporada_tomate))
(at 2 (not(temporada_tomate)))
(at 3 (not(temporada_tomate)))
(at 4 (not(temporada_tomate)))
(at 5 (not(temporada_tomate)))
(at 6 (not(temporada_tomate)))
(at 7 (not(temporada_tomate)))
(at 8 (not(temporada_tomate)))
(at 9 (not(temporada_tomate)))
(at 10 (not(temporada_tomate)))
(at 11 (temporada_tomate))
(at 12 (temporada_tomate))
(at 13 (temporada_tomate))
(at 14 (not(temporada_tomate)))
(at 15 (not(temporada_tomate)))
(at 16 (not(temporada_tomate)))
(at 17 (not(temporada_tomate)))
(at 18 (not(temporada_tomate)))
(at 19 (not(temporada_tomate)))
(at 20 (not(temporada_tomate)))
(at 21 (not(temporada_tomate)))
(at 22 (not(temporada_tomate)))
(at 23 (temporada_tomate))
(at 24 (temporada_tomate))
(at 25 (temporada_tomate))
(at 26 (not(temporada_tomate)))
(at 27 (not(temporada_tomate)))
(at 28 (not(temporada_tomate)))
(at 29 (not(temporada_tomate)))
(at 30 (not(temporada_tomate)))
(at 31 (not(temporada_tomate)))
(at 32 (not(temporada_tomate)))
(at 33 (not(temporada_tomate)))
(at 34 (not(temporada_tomate)))
(at 35 (temporada_tomate))
(at 36 (temporada_tomate))
(at 37 (not(temporada_tomate)))
 (=(cantidad_ha_cultivo Yuca)1)
(at 1 (temporada_yuca))
(at 2 (not(temporada_yuca)))
(at 3 (not(temporada_yuca)))
(at 4 (not(temporada_yuca)))
(at 5 (not(temporada_yuca)))
(at 6 (not(temporada_yuca)))
(at 7 (not(temporada_yuca)))
(at 8 (not(temporada_yuca)))
(at 9 (not(temporada_yuca)))
(at 10 (not(temporada_yuca)))
(at 11 (temporada_yuca))
(at 12 (temporada_yuca))
(at 13 (temporada_yuca))
(at 14 (not(temporada_yuca)))
(at 15 (not(temporada_yuca)))
(at 16 (not(temporada_yuca)))
(at 17 (not(temporada_yuca)))
(at 18 (not(temporada_yuca)))
(at 19 (not(temporada_yuca)))
(at 20 (not(temporada_yuca)))
(at 21 (not(temporada_yuca)))
(at 22 (not(temporada_yuca)))
(at 23 (temporada_yuca))
(at 24 (temporada_yuca))
(at 25 (temporada_yuca))
(at 26 (not(temporada_yuca)))
(at 27 (not(temporada_yuca)))
(at 28 (not(temporada_yuca)))
(at 29 (not(temporada_yuca)))
(at 30 (not(temporada_yuca)))
(at 31 (not(temporada_yuca)))
(at 32 (not(temporada_yuca)))
(at 33 (not(temporada_yuca)))
(at 34 (not(temporada_yuca)))
(at 35 (temporada_yuca))
(at 36 (temporada_yuca))
(at 37 (not(temporada_yuca)))
 (familia_cultivo Papa SOLANACEAS)
 (familia_cultivo Tomate SOLANACEAS)
 (familia_cultivo Yuca LILIACEAS)
(at 1 (parcela_libre Albarran-3_3))
(ultimo_cultivo Albarran-3_3 Ninguna_familia)
(parcelas_vecinas Albarran-3_3 Ninguna_parcela)
(parcelas_vecinas Albarran-3_2 Ninguna_parcela)
(parcelas_vecinas Albarran-2_1 Ninguna_parcela)
(at 1 (parcela_libre Albarran-3_2))
(ultimo_cultivo Albarran-3_2 Ninguna_familia)
(parcelas_vecinas Albarran-3_3 Ninguna_parcela)
(parcelas_vecinas Albarran-3_2 Ninguna_parcela)
(parcelas_vecinas Albarran-2_1 Ninguna_parcela)
(at 37 (parcela_libre Albarran-2_1))
(parcelas_vecinas Albarran-3_3 Ninguna_parcela)
(parcelas_vecinas Albarran-3_2 Ninguna_parcela)
(parcelas_vecinas Albarran-2_1 Ninguna_parcela)
(rotacion Ninguna_familia SOlANACEAS)
(rotacion Ninguna_familia UMBELIFERAS)
(rotacion Ninguna_familia LILIACEAS)
(rotacion Ninguna_familia UMBELIFERAS)
(rotacion Ninguna_familia LEGUMINOSAS)
(rotacion Ninguna_familia CRUCIFERAS)
(rotacion Ninguna_familia COMPUESTAS)
(rotacion Ninguna_familia QUENOPODIACEAS)
(rotacion Ninguna_familia CUCURBITACEAS)
(rotacion Ninguna_familia ALEACEAS)
(rotacion SOlANACEAS Ninguna_familia)
(rotacion UMBELIFERAS Ninguna_familia)
(rotacion LILIACEAS Ninguna_familia)
(rotacion UMBELIFERAS Ninguna_familia)
(rotacion LEGUMINOSAS Ninguna_familia)
(rotacion CRUCIFERAS Ninguna_familia)
(rotacion COMPUESTAS Ninguna_familia)
(rotacion QUENOPODIACEAS Ninguna_familia)
(rotacion CUCURBITACEAS Ninguna_familia)
(rotacion ALEACEAS Ninguna_familia)
(rotacion SOlANACEAS UMBELIFERAS)
(rotacion SOlANACEAS LILIACEAS)
(rotacion UMBELIFERAS COMPUESTAS)
(rotacion UMBELIFERAS QUENOPODIACEAS)
(rotacion UMBELIFERAS CUCURBITACEAS)
(rotacion LILIACEAS COMPUESTAS)
(rotacion LILIACEAS QUENOPODIACEAS)
(rotacion LILIACEAS CUCURBITACEAS)
(rotacion COMPUESTAS LEGUMINOSAS)
(rotacion COMPUESTAS CRUCIFERAS)
(rotacion QUENOPODIACEAS LEGUMINOSAS)
(rotacion QUENOPODIACEAS CRUCIFERAS)
(rotacion CUCURBITACEAS LEGUMINOSAS)
(rotacion CUCURBITACEAS CRUCIFERAS)
(rotacion LEGUMINOSAS SOLANACEAS)
(rotacion CRUCIFERAS SOLANACEAS)
(=(cantidad_ha_parcela Albarran-3_3)8.548)
(=(coeficiente Albarran-3_3 Papa)0.75)
(=(coeficiente Albarran-3_3 Tomate)0.75)
(=(coeficiente Albarran-3_3 Yuca)0.75)
(=(cantidad_ha_parcela Albarran-3_2)8.548)
(=(coeficiente Albarran-3_2 Papa)0.75)
(=(coeficiente Albarran-3_2 Tomate)0.75)
(=(coeficiente Albarran-3_2 Yuca)0.75)
(=(cantidad_ha_parcela Albarran-2_1)5.306)
(=(coeficiente Albarran-2_1 Papa)0.75)
(=(coeficiente Albarran-2_1 Tomate)0.75)
(=(coeficiente Albarran-2_1 Yuca)0.75)
)(:goal (and
(<=(cantidad_ha_cultivo Papa)0)
(<=(cantidad_ha_cultivo Tomate)0)
(<=(cantidad_ha_cultivo Yuca)0)
))
 (:metric minimize (costo))
)